accounts/urls.py
from django.urls import path
from accounts.views import register, user_logout, user_login, profile, delete_user, edit_user, UserPasswordChangeView

app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('login/', user_login, name='login'),
    path('profile/', profile, name='profile'),
    path('profile/delete_user/<int:pk>', delete_user, name='delete_user'),
    path('profile/edit_user/<int:pk>', edit_user, name='edit_user'),
    path('profile/password/change', UserPasswordChangeView.as_view(), name='password_change'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_rating.urls')),
    path('users/', include('accounts.urls')),
]

accounts/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True, verbose_name='email')
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='date of birth')

    def age(self):
        if self.date_of_birth:
            return int((datetime.date.today() - self.date_of_birth).days / 365.25)
        else:
            return None

accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username or email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'your username'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'your password'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'repeat password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'your email'}))
    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'your date of birth'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'date_of_birth')


class DateInput(forms.DateInput):
    input_type = 'date'


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'date_of_birth']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': DateInput(),
        }


class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'your old password'}))
    new_password1 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'your new password'}))
    new_password2 = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'repeat your new password'}))

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

from accounts.forms import UserRegisterForm, UserLoginForm, EditUserForm, PasswordChangingForm
from accounts.models import User


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'You have successfully registered!')
            return redirect('home')
        else:
            messages.error(request, 'Registration error!')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = UserLoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def user_logout(request):
    logout(request)
    messages.success(request, 'You are logged out of your account')
    return redirect('home')


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


@login_required
def delete_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.delete()
        messages.success(request, 'User profile has been deleted')
        return redirect('home')
    return render(request, 'accounts/delete_user.html', {'user': user})


@login_required
def edit_user(request, pk):
    user = User.objects.get(pk=pk)
    if request.method == 'POST':
        form = EditUserForm(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'User data has been changed')
            return redirect('accounts:profile')
        else:
            messages.error(request, form.errors)
    else:
        form = EditUserForm(instance=user)
    return render(request, 'accounts/edit_user.html', {'user': user, 'form': form})


class UserPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/password_change.html'
    form_class = PasswordChangingForm
    success_url = reverse_lazy('accounts:profile')
    success_message = 'Your password has been changed successfully'

accounts/templates/accounts/delete_user.html
{% extends 'base.html' %}

{% block title %}Delete Profile{% endblock %}


{% block content %}

<div class="container">
    <h1>Delete Profile</h1>
    <div class="alert alert-danger" role="alert">
        Are you sure you want to delete your <b>[{{ user }}]</b> Profile?
    </div>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-block">Delete Profile</button>
    </form>
    <br>
    <a class="btn btn-success" href="{% url 'accounts:profile' %}" type="submit">Cancel</a>

</div>
{% endblock %}

accounts/templates/accounts/edit_user.html
{% extends 'base.html' %}

{% block title %}Edit Profile{% endblock %}


{% block content %}

<div class="container">
    <h1>Edit Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger btn-block">Save Changes</button>
        <a class="btn btn-success" href="{% url 'accounts:profile' %}" type="submit">Cancel</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}
Authorization
{% endblock %}


{% block content %}

<div class="container">
    <div class="col-md-5 m-auto">
        <h1>Authorization</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.username }}<br>
            {{ form.password }}<br>
            <button type="submit" class="btn btn-success btn-block">Login</button>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block title %}Password change{% endblock %}


{% block content %}

<div class="container">
    <div class="col-md-5 m-auto">
        <h1>Password change</h1>

        <form method="post">
            {% csrf_token %}

            {% if form.errors %}
            <ul>
                {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    <div>{{ error|escape }}</div>
                </div>
                {% endfor %}
            </ul>
            {% endif %}
            
            {{ form.old_password }}<br>
            {{ form.new_password1 }}<br>
            {{ form.new_password2 }}<br>
            <button type="submit" class="btn btn-danger btn-block">Password change</button>
            <a class="btn btn-success" href="{% url 'accounts:profile' %}" type="submit">Cancel</a>
        </form>

    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}


{% block content %}

<h1>Profile:</h1>
<div class="alert alert-info" role="alert">Your profile: <b>{{ user.username }}</b></div>

<table class="table">
    <thead>
    <tr>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">email</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Age</th>
        <th scope="col">Date of registration</th>
        <th scope="col">Last login</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ user.first_name }}</td>
        <td>{{ user.last_name }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.date_of_birth }}</td>
        <td>{{ user.age }}</td>
        <td>{{ user.date_joined }}</td>
        <td>{{ user.last_login }}</td>
    </tr>
    </tbody>
</table>

<a href="{% url 'accounts:edit_user' pk=user.id %}" class="btn btn-primary btn-sm">Edit Profile</a>
<a href="{% url 'accounts:delete_user' pk=user.id %}" class="btn btn-danger btn-sm">Delete Profile</a>
<a href="{% url 'accounts:password_change' %}" class="btn btn-secondary btn-sm">Password change</a>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}
Sign Up
{% endblock %}


{% block content %}
<div class="container">
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.username }}<br>
        {{ form.password1 }}<br>
        {{ form.password2 }}<br>
        {{ form.email }}<br>
        {{ form.date_of_birth }}<br>
        <button type="submit" class="btn btn-success btn-block">Sign Up</button>
    </form>
</div>
{% endblock %}