accounts/urls.py
from django.urls import path
from accounts.views import register, user_logout, user_login, profile, delete_user, edit_user, UserPasswordChangeView

app_name = 'accounts'
urlpatterns = [
    path('register/', register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('login/', user_login, name='login'),
    path('profile/', profile, name='profile'),
    path('profile/delete_user/<int:pk>', delete_user, name='delete_user'),
    path('profile/edit_user/<int:pk>', edit_user, name='edit_user'),
    path('profile/password/change', UserPasswordChangeView.as_view(), name='password_change'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_rating.urls')),
    path('users/', include('accounts.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Movie Rating App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        Welcome, {{ user.username }}
        &ensp;<a class="btn btn-success" href="{% url 'accounts:profile' %}" type="submit">Profile: {{ user.username }}</a>
        &ensp;<a class="btn btn-warning" href="{% url 'accounts:logout' %}" type="submit">Logout</a>
        {% else %}
        <a class="btn btn-warning" href="{% url 'accounts:login' %}" type="submit">Login</a>&ensp;
        <a class="btn btn-danger" href="{% url 'accounts:register' %}" type="submit">Sign Up</a>
        {% endif %}
    </div>
</nav>

{% if messages %}
{% for message in messages %}
<div class="container">
    <div class="alert alert-success" role="alert">
        {{ message.tag }}
        {{ message|safe }}
    </div>
</div>
{% endfor %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-9 m-auto">
            {% block content %}
            {% endblock %}

            {% if page_obj.has_other_pages %}
            <nav aria-label="...">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                    </li>
                    {% endif %}
                    {% for p in page_obj.paginator.page_range %}
                    {% if page_obj.number == p %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                    </li>
                    {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3%}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ p }}">{{ p }}<span class="sr-only"></span></a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}

        </div>
    </div>
</div>
</body>

</html>